### ISSUE TITLE
Código JPA básico

### ISSUE THREAD

**Issue by santunioni** [danielkv7/digital-innovation-one#1]
Olá, Daniel.

Os códigos da aula JPA BÁSICO não estão presentes no repositório. No lugar da pasta com os códigos está um hardlink. Veja: https://github.com/danielkv7/digital-innovation-one/tree/master/Aula_JPA_basico

Você poderia postar os códigos?
Obrigado

**Comment by danielkv7** [comment]
> Olá, Daniel.
> 
> Os códigos da aula JPA BÁSICO não estão presentes no repositório. No lugar da pasta com os códigos está um hardlink. Veja: https://github.com/danielkv7/digital-innovation-one/tree/master/Aula_JPA_basico
> 
> Você poderia postar os códigos?
> Obrigado

Olá!

Realmente não está muito correto a disposição desse repositório. Eu irei corrigir já com um link para o repositório no qual o código está hospedado que é este -> https://github.com/danielkv7/jpa-basico

Obrigado por indicar esse falha.

**Comment by santunioni** [comment]
> > Olá, Daniel.
> > Os códigos da aula JPA BÁSICO não estão presentes no repositório. No lugar da pasta com os códigos está um hardlink. Veja: https://github.com/danielkv7/digital-innovation-one/tree/master/Aula_JPA_basico
> > Você poderia postar os códigos?
> > Obrigado
> 
> Olá!
> 
> Realmente não está muito correto a disposição desse repositório. Eu irei corrigir já com um link para o repositório no qual o código está hospedado que é este -> https://github.com/danielkv7/jpa-basico
> 
> Obrigado por indicar esse falha.

valeu Daniel!
